### ISSUE TITLE
Error when attempting to parse xhr response text (Unexpected token < in JSON at position 0)

### ISSUE THREAD

**Issue by baddy1000** [terminal42/contao-fineuploader#53] opened 2018-12-17 10:55 UTC
Been trying to get this running. 

Added this to tl_member.php 

```
$GLOBALS['TL_DCA']['tl_member']['fields']['avatarUpload'] = array
(
    'label'                   => &$GLOBALS['TL_LANG']['tl_member']['avatarUpload'],
    'exclude'                 => true,
    'inputType'               => 'fineUploader',
    'eval'                    => array
    (
    	'debug'				=> true,
    	'feEditable'		=> true,
    	'feGroup'			=> 'personal',
    	'tl_class'			=> 'w50 wizard clr',
        'storeFile'         => true,              
        'multiple'          => true,              
        'uploadFolder'      => 'files/uploads',   
        'useHomeDir'        => true,  
        'uploaderConfig'    => "['debug': true]", 
        'uploaderLimit'     => 1,         
        'addToDbafs'        => true,        
        'extensions'        => 'jpg,jpeg,gif,png', 
        'minlength'         => 1024,     
        'maxlength'         => 10240000,     
        'maxWidth'          => 1024,      
        'maxHeight'         => 1024,       
        'doNotOverwrite'    => true,           
        'uploadButtonLabel' => 'Upload images',  

        'chunking'          => true,            
        'chunkSize'         => 2000000,     
        'concurrent'        => true,               
        'maxConnections'    => 30, 
        'directUpload' => false,
        'imageSize'         => [128, 128, 'center_center']
    ),
    'sql'                     => "blob NULL"
);
```

When I try uploading something in the Front End, it aborts the upload somewhat midway and gives me this error message.
![image](https://user-images.githubusercontent.com/15890453/50082737-f626e100-01f1-11e9-930d-6e09932b2cfe.png)

**Comment by havutcuoglu** [comment] 2019-04-05 09:05
The error is reproducible under Contao 4.6.6. See the screenshots below.

<img width="545" alt="Bildschirmfoto 2019-04-05 um 11 03 54" src="https://user-images.githubusercontent.com/11348417/55616640-8cc3e180-5792-11e9-8395-e55010cd7390.png">
<img width="525" alt="Bildschirmfoto 2019-04-05 um 10 50 59" src="https://user-images.githubusercontent.com/11348417/55616648-8f263b80-5792-11e9-9150-ce7be477c63f.png">

**Comment by qzminski** [comment] 2019-08-16 10:25
@havutcuoglu what does the log say? In `/var/logs/` folder.

**Comment by havutcuoglu** [comment] 2019-08-18 07:54
@qzminski sorry, but the project is already live (since 2019 Mai) and the logs are cleared. 😔
I can't remember how I fixed this Problem, but I will give you feedback when I can get more information for you.

**Comment by qzminski** [comment] 2019-08-20 07:21
Sure, no problem. I will close this as I cannot reproduce the issue and once you know what was going on, please do open the ticket 🙂

**Closed by qzminski** 2019-08-20 07:21 UTC
Labels: bug
